const { app, BrowserWindow, dialog, ipcMain, protocol, Menu } = require('electron');
const { spawn } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
let engine; let token; let mainWindow; let projectFile; const sources = new Map();
const settingsPath = () => path.join(app.getPath('userData'), 'settings.json');
const defaults = { language: 'tr', theme: 'system', maskColor: '#ff3b6b', maskOpacity: .42 };
const readSettings = () => { try { return {...defaults, ...JSON.parse(fs.readFileSync(settingsPath(), 'utf8'))}; } catch { return defaults; } };
const writeAtomic = (file, data) => { const tmp = `${file}.tmp`; fs.writeFileSync(tmp, data); fs.renameSync(tmp, file); };
function request(route, options={}) { return fetch(`http://127.0.0.1:${engine.port}${route}`, { ...options, headers: {'X-PixelMend-Token': token, ...(options.headers || {})} }); }
async function api(route, options={}) { const response = await request(route, options); if (!response.ok) { let detail = `Motor hatası (${response.status})`; try { detail = (await response.json()).detail || detail; } catch {} throw new Error(detail); } return response; }
async function startEngine() {
  token = crypto.randomBytes(32).toString('hex');
  const executable = app.isPackaged ? path.join(process.resourcesPath, 'engine', 'pixelmend-engine') : path.join(__dirname, '../../../engine/.venv/bin/python');
  const args = app.isPackaged ? [] : ['-m', 'pixelmend_engine'];
  engine = spawn(executable, args, {env: {...process.env, PIXELMEND_SESSION_TOKEN: token}, stdio: ['ignore', 'pipe', 'pipe']});
  const line = await new Promise((resolve, reject) => { let buf=''; engine.stdout.on('data', d => { buf += d; const i=buf.indexOf('\n'); if(i>=0) resolve(buf.slice(0,i)); }); engine.once('error', reject); setTimeout(() => reject(new Error('Engine startup timed out')), 15000); });
  engine.port = JSON.parse(line).port;
  await api('/health');
}
function createWindow() { const window = new BrowserWindow({width: 1320, height: 900, minWidth: 760, minHeight: 600, webPreferences: {preload:path.join(__dirname,'preload.cjs'), contextIsolation:true, sandbox:true, nodeIntegration:false}}); window.loadFile(path.join(__dirname,'../dist/index.html')); return window; }
app.whenReady().then(async () => { protocol.handle('pixelmend', async requestUrl => { const key = requestUrl.url.replace('pixelmend://',''); const value=sources.get(key); return new Response(value || '', {status:value ? 200 : 404, headers:{'Content-Type':'image/png'}}); }); await startEngine(); const window=mainWindow=createWindow();
 ipcMain.handle('pixelmend:open-image', async () => { const result=await dialog.showOpenDialog(window,{properties:['openFile'],filters:[{name:'Images',extensions:['png','jpg','jpeg','webp','tif','tiff']}]}); if(result.canceled) return null; const form=new FormData(); form.append('image', new Blob([fs.readFileSync(result.filePaths[0])]), path.basename(result.filePaths[0])); const asset=await (await api('/assets',{method:'POST',body:form})).json(); const preview=await (await api(`/assets/${asset.asset_id}/preview`)).arrayBuffer(); sources.set(`asset/${asset.asset_id}`,preview); return {...asset, preview:`pixelmend://asset/${asset.asset_id}`}; });
 ipcMain.handle('pixelmend:start-job', async (_e, payload) => { if(!['remove','upscale'].includes(payload.operation)) throw new Error('Geçersiz işlem'); const form=new FormData(); form.append('asset_id',payload.assetId); form.append('algorithms',JSON.stringify([payload.operation==='upscale'?'lanczos':'lama'])); form.append('scale',payload.operation==='upscale'?'2':'1'); if(payload.operation==='upscale'){if(!Number.isInteger(payload.targetWidth)||!Number.isInteger(payload.targetHeight)||payload.targetWidth<1||payload.targetHeight<1||payload.targetWidth*payload.targetHeight>50_000_000)throw new Error('Geçersiz çıktı ölçüsü');form.append('target_width',String(payload.targetWidth));form.append('target_height',String(payload.targetHeight));} if(payload.mask) form.append('mask',new Blob([Buffer.from(payload.mask,'base64')]),'mask.png'); return (await api('/jobs',{method:'POST',body:form})).json(); });
 ipcMain.handle('pixelmend:job', async (_e,id) => (await api(`/jobs/${id}`)).json()); ipcMain.handle('pixelmend:cancel',async(_e,id)=>(await api(`/jobs/${id}/cancel`,{method:'POST'})).json());
 ipcMain.handle('pixelmend:result', async (_e,j,r,f='PNG') => { const bytes=await (await api(`/jobs/${j}/results/${r}?format=${f}`)).arrayBuffer(); const key=`result/${j}/${r}`; sources.set(key,bytes); return `pixelmend://${key}`; });
 ipcMain.handle('pixelmend:continue-result', async (_e,j,r) => { const asset=await (await api(`/jobs/${j}/results/${r}/asset`,{method:'POST'})).json(); const preview=await (await api(`/assets/${asset.asset_id}/preview`)).arrayBuffer(); sources.set(`asset/${asset.asset_id}`,preview); return {...asset,preview:`pixelmend://asset/${asset.asset_id}`}; });
 ipcMain.handle('pixelmend:save', async (_e,j,r,f='PNG') => { const save=await dialog.showSaveDialog(window,{defaultPath:`PixelMend.${f.toLowerCase()}`}); if(save.canceled)return null; const bytes=await (await api(`/jobs/${j}/results/${r}?format=${f}`)).arrayBuffer(); fs.writeFileSync(save.filePath,Buffer.from(bytes)); return save.filePath; });
 ipcMain.handle('pixelmend:save-rendered', async (_e, base64, format='PNG') => { if(typeof base64 !== 'string' || !/^[A-Za-z0-9+/=]+$/.test(base64) || base64.length > 700_000_000) throw new Error('project_invalid'); const save=await dialog.showSaveDialog(window,{defaultPath:`PixelMend.${format.toLowerCase()}`}); if(save.canceled)return false; fs.writeFileSync(save.filePath,Buffer.from(base64,'base64')); return true; });
 ipcMain.handle('pixelmend:settings', () => readSettings()); ipcMain.handle('pixelmend:set-settings', (_e, value) => writeAtomic(settingsPath(), JSON.stringify({...defaults,...value})));
 ipcMain.handle('pixelmend:export-source', (_e, id) => { if(typeof id!=='string'||!/^[a-f0-9]{32}$/.test(id)) throw new Error('Geçersiz görsel'); const bytes=sources.get(`asset/${id}`);if(!bytes)throw new Error('Görsel bulunamadı');return `data:image/png;base64,${Buffer.from(bytes).toString('base64')}`; });
 ipcMain.handle('pixelmend:save-project', async (_e, document, saveAs) => { if(!document || document.version !== 1) throw new Error('project_invalid'); if(saveAs || !projectFile) { const chosen=await dialog.showSaveDialog(window,{defaultPath:'PixelMend.pixelmend',filters:[{name:'PixelMend proje',extensions:['pixelmend']}]}); if(chosen.canceled) return false; projectFile=chosen.filePath; } const ids=[...new Set(JSON.stringify(document).match(/pixelmend:\/\/(?:asset|result)\/[^"\\]+/g)||[])]; const blobs={}; for(const uri of ids){const key=uri.replace('pixelmend://','');if(sources.has(key)) blobs[uri]=Buffer.from(sources.get(key)).toString('base64');} writeAtomic(projectFile,JSON.stringify({format:'pixelmend',version:1,document,blobs})); return true; });
 ipcMain.handle('pixelmend:open-project', async () => { const chosen=await dialog.showOpenDialog(window,{properties:['openFile'],filters:[{name:'PixelMend proje',extensions:['pixelmend']}]});if(chosen.canceled)return null;let saved;try{saved=JSON.parse(fs.readFileSync(chosen.filePaths[0],'utf8'))}catch{throw new Error('project_invalid')}if(saved?.format!=='pixelmend'||saved.version!==1||!saved.document||typeof saved.blobs!=='object')throw new Error('project_invalid');const document=structuredClone(saved.document), replacements=new Map();const revive=async photo=>{if(!photo?.uri||replacements.has(photo.uri))return replacements.get(photo?.uri);const b64=saved.blobs[photo.uri];if(typeof b64!=='string'||b64.length>700000000)throw new Error('project_invalid');const revived=await (async()=>{const form=new FormData();form.append('image',new Blob([Buffer.from(b64,'base64')]),'project.png');const asset=await (await api('/assets',{method:'POST',body:form})).json();const preview=await (await api(`/assets/${asset.asset_id}/preview`)).arrayBuffer();sources.set(`asset/${asset.asset_id}`,preview);return {id:asset.asset_id,uri:`pixelmend://asset/${asset.asset_id}`,width:asset.width,height:asset.height}})();replacements.set(photo.uri,revived);return revived};for(const snapshot of [...document.history.past,document.history.present,...document.history.future])snapshot.photo=await revive(snapshot.photo);document.original=await revive(document.original);projectFile=chosen.filePaths[0];return document; });
 Menu.setApplicationMenu(Menu.buildFromTemplate([{label:'PixelMend',submenu:[{label:'Ayarlar',accelerator:'Cmd+,',click:()=>mainWindow.webContents.send('pixelmend:action','settings')},{role:'quit'}]},{label:'Düzen',submenu:[{label:'Geri al',accelerator:'Cmd+Z',click:()=>mainWindow.webContents.send('pixelmend:action','undo')},{label:'Yinele',accelerator:'Shift+Cmd+Z',click:()=>mainWindow.webContents.send('pixelmend:action','redo')}]}])); });
app.on('window-all-closed',()=>app.quit()); app.on('before-quit',()=>engine?.kill('SIGTERM'));
