import React, { useEffect, useRef, useState } from 'react'; import { createRoot } from 'react-dom/client'; import { StrokeHistory, imagePoint } from './strokes'; import './style.css';
declare global { interface Window { pixelmend: any } }
const history = new StrokeHistory();
function App() { const [asset,setAsset]=useState<any>(); const [mode,setMode]=useState<'paint'|'erase'>('paint'); const [brush,setBrush]=useState(28); const [job,setJob]=useState<any>(); const [result,setResult]=useState<string>(); const canvas=useRef<HTMLCanvasElement>(null); const drawing=useRef<[number,number][]>([]);
 const redraw=()=>{ if(!asset||!canvas.current)return; const c=canvas.current,ctx=c.getContext('2d')!; c.width=asset.width;c.height=asset.height;ctx.clearRect(0,0,c.width,c.height);for(const s of history.strokes){ctx.globalCompositeOperation=s.mode==='erase'?'destination-out':'source-over';ctx.strokeStyle='white';ctx.lineWidth=s.radius;ctx.lineCap='round';ctx.beginPath();s.points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}ctx.globalCompositeOperation='source-over';};
 useEffect(redraw,[asset,mode,brush]); useEffect(()=>{let active=true; if(!job)return; const poll=async()=>{const s=await window.pixelmend.job(job.job_id);if(!active)return;if(s.status==='completed'){const uri=await window.pixelmend.result(job.job_id,s.result_ids[0]);setResult(uri);}else if(!['failed','cancelled'].includes(s.status))setTimeout(poll,120)};poll();return()=>{active=false}},[job]);
 const open=async()=>{const a=await window.pixelmend.openImage();if(a){history.clear();setAsset(a);setResult(undefined);setJob(undefined)}};
 const pointer=(event:React.PointerEvent)=>{if(!asset)return;const p=imagePoint(event.clientX,event.clientY,event.currentTarget.getBoundingClientRect(),asset.width,asset.height);if(event.type==='pointerdown'){event.currentTarget.setPointerCapture(event.pointerId);drawing.current=[p]}else if(event.type==='pointermove'&&drawing.current.length)drawing.current.push(p);else if(event.type==='pointerup'){history.add({mode,radius:brush,points:drawing.current});drawing.current=[];redraw();}};
 const process=async(algorithm='opencv_telea')=>{if(!asset)return;redraw();const c=canvas.current!;const mask=c.toDataURL('image/png').split(',')[1];setJob(await window.pixelmend.startJob({assetId:asset.asset_id,algorithms:[algorithm],mask}));};
 return <main><header><h1>PixelMend</h1><button onClick={open}>Görsel Aç</button><button disabled={!asset} onClick={()=>process()}>Sil</button><button disabled={!job} onClick={()=>window.pixelmend.cancel(job.job_id)}>İptal</button><button disabled={!result} onClick={()=>window.pixelmend.save(job.job_id,job.result_ids[0],'PNG')}>Kaydet</button></header><section className="workspace"><aside><label>Fırça {brush}px<input type="range" min="2" max="160" value={brush} onChange={e=>setBrush(+e.target.value)}/></label><button onClick={()=>setMode('paint')} aria-pressed={mode==='paint'}>Boya</button><button onClick={()=>setMode('erase')} aria-pressed={mode==='erase'}>Silgi</button><button onClick={()=>{history.undo();redraw()}}>Geri al</button><button onClick={()=>{history.redo();redraw()}}>Yinele</button><button onClick={()=>{history.clear();redraw()}}>Maskeyi temizle</button><hr/><button disabled={!asset} onClick={()=>process('lama')}>LaMa</button><button disabled={!asset} onClick={()=>window.pixelmend.startJob({assetId:asset.asset_id,algorithms:['lanczos'],scale:2}).then(setJob)}>Lanczos 2×</button></aside><article>{asset?<div className="canvas"><img src={result||asset.preview}/><canvas ref={canvas} onPointerDown={pointer} onPointerMove={pointer} onPointerUp={pointer}/></div>:<div className="empty">Bir görsel açın veya sürükleyip bırakın.</div>}{job&&<p role="status">İş durumu: {job.status||'çalışıyor'}</p>}</article></section></main> } createRoot(document.getElementById('root')!).render(<App/>);
